import { WAIT_FOR_ACTION } from 'redux-wait-for-action'

export const TYPES = {
  ME: {
    UPDATE: '@ME/UPDATE_PROFILE',
    LOGOUT: '@ME/LOGOUT',
    LOGOUT_SUCCESS: '@ME/LOGOUT_SUCCESS',
  },
  LOCAL: {
    UPDATE: '@LOCAL/UPDATE',
  },
  SCREEN: {
    SHOW_LOADING: '@LOCAL/SHOW_LOADING',
    HIDE_LOADING: '@LOCAL/HIDE_LOADING',
    CHANGE_SCREEN: '@LOCAL/CHANGE_SCREEN',
  },
  READING: {
    TRANSLATION: '@BIBLE/TRANSLATION',
  },
  GROUPS: {
    SYNC: '@GROUPS/SYNC',
  },
  CAMPUS: {
    SYNC: '@CAMPUS/SYNC',
  },
  GROUP: {
    RELOAD_DIRECT_MESSAGES: '@GROUP/RELOAD_DIRECT_MESSAGES',
    UPDATE_DIRECT_MESSAGES_UNREAD_COUNT: '@GROUP/UPDATE_DIRECT_MESSAGES_UNREAD_COUNT',
    UPDATE_GROUP_MESSAGES_UNREAD_COUNT: '@GROUP/UPDATE_GROUP_MESSAGES_UNREAD_COUNT',
    RESET_DIRECT_MESSAGES_UNREAD_COUNT: '@GROUP/RESET_DIRECT_MESSAGES_UNREAD_COUNT',
    OPEN_GROUP_SCREEN: '@GROUP/OPEN_GROUP_SCREEN',
    UPDATE: '@GROUP/UPDATE',
    CLOSE_GROUP_SCREEN: '@GROUP/CLOSE_GROUP_SCREEN',
    RELOAD_GROUP_CHAT: '@GROUP/RELOAD_GROUP_CHAT',
    CREATE_GROUP: '@GROUP/CREATE_GROUP',
    ADD_SMP_RESPONSES: '@GROUP/ADD_SMP_RESPONSES',
    SYNC_ACTIONS: '@GROUP/SYNC_ACTIONS',
    LOAD_SCORE: '@GROUP/LOAD_SCORE',
    GET_UNREAD_DISCUSSIONS: '@GROUP/GET_UNREAD_DISCUSSIONS',
  },
  ORGANISATION: {
    GET_ORG: '@ORGANISATIONS/GET_ORG',
    GET_TITHINGS: '@ORGANISATIONS/GET_TITHINGS',
    GET_CAMPAIGNS: '@ORGANISATIONS/GET_CAMPAIGNS',
    UPDATE: '@ORGANISATIONS/UPDATE',
  },
  ACTION_STEPS: {
    LOAD: '@ACTION_STEPS/LOAD',
    RECEIVE_DATA: '@ACTION_STEPS/RECEIVE_DATA',
    CLEAR: '@ACTION_STEPS/CLEAR',
    MARK_AS_READ: '@ACTION_STEPS/MARK_AS_READ',
    RECEIVE_ACTIVE_ACTION_STEP: '@ACTION_STEPS/RECEIVE_ACTION_STEP',
    SYNC_ACTIVE_ACTION_STEP: '@ACTION_STEPS/SYNC_ACTIVE_ACTION_STEP',
  },
  FOLLOW_UPS: {
    LOAD: '@FOLLOW_UPS/LOAD',
    RECEIVE_DATA: '@FOLLOW_UPS/RECEIVE_DATA',
    CLEAR: '@FOLLOW_UPS/CLEAR',
    MARK_AS_READ: '@FOLLOW_UPS/MARK_AS_READ',
    VIEW_ALL: '@FOLLOW_UPS/VIEW_ALL',
    RECEIVE_DAILY_FLOW: '@FOLLOW_UPS/RECEIVE_DAILY_FLOW',
  },
  GROUP_ACTIONS: {
    LOAD: '@GROUP_ACTIONS/LOAD',
    RECEIVE_DATA: '@GROUP_ACTIONS/RECEIVE_DATA',
    VIEW: '@GROUP_ACTIONS/VIEW',
    VIEW_ALL: '@GROUP_ACTIONS/VIEW_ALL',
    CLEAR: '@GROUP_ACTIONS/CLEAR',
  },
  INVITES: {
    JOIN: {
      PENDING: '@INVITE_JOIN_GROUP',
      ACCEPTED: '@INVITE_JOIN_GROUP_ACCEPTED',
      SUCCESS: '@INVITE_JOIN_GROUP_SUCCESS',
      REJECTED: '@INVITE_JOIN_GROUP_REJECTED',
    },
    FOLLOW: {
      PENDING: '@INVITE_FOLLOW',
      ACCEPTED: '@INVITE_FOLLOW_ACCEPTED',
      SUCCESS: '@INVITE_FOLLOW_SUCCESS',
      REJECTED: '@INVITE_FOLLOW_REJECTED',
    },
    SENT: '@INVITES/SENT',
    FOLLOWED: '@INVITES/FOLLOWED',
    FOLLOWED_INVITE: '@INVITES/FOLLOWED_INVITE',
  },
  SYNC: '@SYNC',
  TRANSLATIONS: {
    SYNC: '@TRANSLATIONS/SYNC',
    VERSION: {
      UPDATE: '@TRANSLATIONS/VERSION/UPDATE',
    },
  },
  ONBOARDING: {
    SET_GROUP_ID: '@ONBOARDING/SET_GROUP_ID',
    SET_NAME: '@ONBOARDING/SET_NAME',
    SET_AVATAR: '@ONBOARDING/SET_AVATAR',
    SET_ANSWERS: '@ONBOARDING/SET_ANSWERS',
    SET_INVITE_ID: '@ONBOARDING/SET_INVITE_ID',
    SET_SMART_PLAN: '@ONBOARDING/SET_SMART_PLAN',
    SET_QUICK_STUDY_PLAN: '@ONBOARDING/SET_QUICK_STUDY_PLAN',
    SET_ADVANCED_STUDY_PLAN: '@ONBOARDING/SET_ADVANCED_STUDY_PLAN',
    SET_START_DATE: '@ONBOARDING/SET_START_DATE',
    SET_END_DATE: '@ONBOARDING/SET_END_DATE',
    SET_ORG_ID: '@ONBOARDING/SET_ORG_ID',
    CLEAR: '@ONBOARDING/CLEAR',
  },
  SETTINGS: {
    UPDATE: '@SETTINGS/UPDATE',
  },
}

export const logout = () => {
  return {
    type: TYPES.ME.LOGOUT,
    [WAIT_FOR_ACTION]: TYPES.ME.LOGOUT_SUCCESS,
  }
}
