import * as admin from 'firebase-admin'
import init from './shared/i18n'

// Firebase
admin.initializeApp()
init()

// CFs
// admin
export { default as donationOnCreate } from './admin/actions/donationOnCreate'
export { default as donationOnDelete } from './admin/actions/donationOnDelete'
export { default as func_attach_campaign_video } from './admin/https/func_attach_campaign_video'
export { default as func_change_role_access } from './admin/https/func_change_role_access'
export { default as func_change_tithing_status } from './admin/https/func_change_tithing_status'
export { default as func_check_connect_stripe } from './admin/https/func_check_connect_stripe'
export { default as func_connect_stripe } from './admin/https/func_connect_stripe'
export { default as func_create_campaign } from './admin/https/func_create_campaign'
export { default as func_create_campus } from './admin/https/func_create_campus'
export { default as func_create_campus_access } from './admin/https/func_create_campus_access'
export { default as func_create_tithing } from './admin/https/func_create_tithing'
export { default as func_delete_campaign } from './admin/https/func_delete_campaign'
export { default as func_delete_member } from './admin/https/func_delete_member'
export { default as func_delete_member_access } from './admin/https/func_delete_member_access'
export { default as func_delete_tithing } from './admin/https/func_delete_tithing'
export { default as func_export_donation } from './admin/https/func_export_donation'
export { default as func_export_members } from './admin/https/func_export_members'
export { default as func_find_member } from './admin/https/func_find_member'
export { default as func_generate_plan_from_sermon } from './admin/https/func_generate_plan_from_sermon'
export { default as func_get_campaigns } from './admin/https/func_get_campaigns'
export { default as func_get_campaign_details } from './admin/https/func_get_campaign_details'
export { default as func_get_campus } from './admin/https/func_get_campus'
export { default as func_get_campuses_with_tithing } from './admin/https/func_get_campuses_with_tithing'
export { default as func_get_campus_access } from './admin/https/func_get_campus_access'
export { default as func_get_dashboard_account } from './admin/https/func_get_dashboard_account'
export { default as func_get_donations } from './admin/https/func_get_donations'
export { default as func_get_giving_reports } from './admin/https/func_get_giving_reports'
export { default as func_get_groups } from './admin/https/func_get_groups'
export { default as func_get_group_detail } from './admin/https/func_get_group_details'
export { default as func_get_group_social_posts } from './admin/https/func_get_group_social_posts'
export { default as func_get_members } from './admin/https/func_get_members'
export { default as func_get_members_campus } from './admin/https/func_get_members_campus'
export { default as func_get_plan } from './admin/https/func_get_plan'
export { default as func_get_profile } from './admin/https/func_get_profile'
export { default as func_get_reports } from './admin/https/func_get_reports'
export { default as func_get_tithings } from './admin/https/func_get_tithings'
export { default as func_get_tithing_details } from './admin/https/func_get_tithing_details'
export { default as func_get_user_donation_history } from './admin/https/func_get_user_donation_history'
export { default as func_login_email } from './admin/https/func_login_email'
export { default as func_make_donate } from './admin/https/func_make_donate'
export { default as func_publish_campaign } from './admin/https/func_publish_campaign'
export { default as func_remove_campaign_video } from './admin/https/func_remove_campaign_video'
export { default as func_remove_dashboard_access } from './admin/https/func_remove_dashboard_access'
export { default as func_remove_dashboard_user } from './admin/https/func_remove_dashboard_user'
export { default as func_search_giving } from './admin/https/func_search_giving'
export { default as func_send_invite } from './admin/https/func_send_invite'
export { default as func_send_notifications } from './admin/https/func_send_notifications'
export { default as func_update_campaign } from './admin/https/func_update_campaign'
export { default as func_update_campus } from './admin/https/func_update_campus'
export { default as func_update_donate } from './admin/https/func_update_donate'
export { default as func_update_organisation_default } from './admin/https/func_update_organisation_default'
export { default as func_update_tithing } from './admin/https/func_update_tithing'
export { default as func_user_permissions } from './admin/https/func_user_permissions'
export { default as func_verify_invite } from './admin/https/func_verify_invite'
export { default as func_confirm_checkout } from './stripe/func_confirm_checkout'
// checkout
export { default as auth_onCreate } from './auth/onCreate'
export { default as auth_onDelete } from './auth/onDelete'
export { default as campus_onCreate } from './campusAction/onCreate'
export { default as schedfunc_dataBackup } from './cronjobs/dataBackup'
export { default as schedfunc_remindActionStep } from './cronjobs/remindActionStep'
export { default as schedfunc_remindDailyFlowNotification } from './cronjobs/remindDailyFlowNotification'
export { default as schedfunc_remindPrayNotification } from './cronjobs/remindPrayNotification'
export { default as schedfunc_expires_subscriptions } from './cronjobs/schedfunc_expires_subscriptions'
export { default as sub_google_iap } from './cronjobs/sub_google_iap'
export { default as schedfunc_tasks } from './cronjobs/tasks'
export { default as pubsubfunc_updateBadgeCount } from './cronjobs/updateBadgeCount'
export { default as schedfunc_updateGroupScore } from './cronjobs/updateGroupScore'
export { default as schedfunc_updateMixpanel } from './cronjobs/updateMixpanel'
export { default as donate_onUpdate } from './donate/onUpdate'
export { default as follow_ups_onCreate } from './followUps/onCreate'
export { default as follow_ups_onUpdate } from './followUps/onUpdate'
export { default as group_onCreate } from './group/onCreate'
export { default as group_onDelete } from './group/onDelete'
export { default as group_onUpdate } from './group/onUpdate'
export { default as groupAction_onCreate } from './groupAction/onCreate'
// sync organisation
export { default as groupAction_onWrite } from './groupAction/onWrite'
export { default as func_apply_plan_to_group } from './https/func_apply_plan_to_group'
export { default as func_check_overlap_plans } from './https/func_check_overlap_plans'
export { default as func_create_smart_plan } from './https/func_create_smart_plan'
export { default as func_delete_study_plan } from './https/func_delete_study_plan'
export { default as func_end_study_plan } from './https/func_end_study_plan'
export { default as func_generate_code } from './https/func_generate_code'
export { default as func_generate_invite_qr_code } from './https/func_generate_invite_qr_code'
export { default as func_get_invite } from './https/func_get_invite'
export { default as func_get_invite_link } from './https/func_get_invite_link'
export { default as func_get_leader_prompts } from './https/func_get_leader_prompts'
export { default as func_get_unread_action_step } from './https/func_get_unread_action_step'
export { default as func_get_weekly_review } from './https/func_get_weekly_review'
export { default as func_invite_accept } from './https/func_invite_accept'
export { default as func_invite_get } from './https/func_invite_get'
export { default as func_join_group } from './https/func_join_group'
export { default as func_remove_group_member } from './https/func_remove_group_member'
export { default as func_request_subscription } from './https/func_request_subscription'
export { default as func_share_plan_to_org } from './https/func_share_plan_to_org'
export { default as func_sync_members_to_stream } from './https/func_sync_members_to_stream'
export { default as func_trigger_change_active_plan } from './https/func_trigger_change_active_plan'
export { default as func_trigger_create_message } from './https/func_trigger_create_message'
export { default as func_update_group_activity_score } from './https/func_update_group_activity_score'
export { default as func_update_group_study_progress } from './https/func_update_group_study_progress'
export { default as func_update_plan_start_date } from './https/func_update_plan_start_date'
export { default as func_verify_receipt } from './https/func_verify_receipt'
export { default as hook_apple_iap } from './https/hook_apple_iap'
export { default as hook_streamIO } from './https/hook_streamIO'
export { default as v2_func_apply_plan_to_group } from './https/v2_func_apply_plan_to_group'
export { default as iap_onUpdate } from './iap/onUpdate'
export { default as func_check_providers } from './master/func_check_providers'
export { default as func_update_organisation_details } from './admin/https/func_update_organisation_details'

// master
export { default as func_create_org } from './master/func_create_org'
export { default as func_invite_to_org } from './master/func_invite_to_org'
export { default as func_verify_email } from './master/func_verify_email'
export { default as plan_onCreate } from './plan/onCreate'
export { default as plan_onDelete } from './plan/onDelete'
export { default as plan_onUpdate } from './plan/onUpdate'
export { default as planProgress_onWrite } from './planProgress/onWrite'
export { default as groupScore_onUpdate } from './score/onUpdate'
export {
  settings_fixThreadBlockIndex,
  settings_groupScore_patchData,
  settings_unreadThreads_migrationData,
} from './settings/onUpdate'
export { default as storage_onFinalize } from './storage/onFinalize'
export { default as func_add_card } from './stripe/func_add_card'
export { default as func_create_checkout } from './stripe/func_create_checkout'
export { default as func_delete_card } from './stripe/func_delete_card'
export { default as func_get_cards } from './stripe/func_get_cards'
export { default as bug_onCreate } from './bug/onCreate'
export { default as bug_onUpdate } from './bug/onUpdate'
export { default as feedback_onCreate } from './feedback/onCreate'
export { default as feedback_onUpdate } from './feedback/onUpdate'
// Stripe
export { default as func_request_intent } from './stripe/func_request_intent'
export { default as func_stripe_checkout_webhook } from './stripe/func_stripe_checkout_webhook'
export { default as func_update_card } from './stripe/func_update_card'
export { default as user_onDelete } from './user/onDelete'
export { default as user_onUpdate } from './user/onUpdate'
export { default as cron_experiment_emails } from './video/cron_experiment_emails'
export { default as func_generate_plan } from './video/func_generate_plan'
export { default as func_log_ga_event } from './video/func_log_ga_event'
export { default as func_donate_checkout_webhook } from './stripe/func_donate_checkout_webhook'
// Video
export { default as func_process_video } from './video/func_process_video'
export { default as func_remotion_webhook } from './video/func_remotion_webhook'
export { default as func_send_invite_sms } from './video/func_send_invite_sms'
export { default as func_send_sms } from './video/func_send_sms'
export { default as func_transcribe_webhook } from './video/func_transcribe_webhook'
export { default as func_onboard } from './video/func_onboard'
export { default as func_check_onboard } from './video/func_check_onboard'
export { default as func_carry_donate_setup } from './stripe/func_carry_donate_setup'
export { default as func_carry_donate_update } from './stripe/func_carry_donate_update'
export { default as func_carry_donate_webhook } from './stripe/func_carry_donate_webhook'
