export enum WeeklyReviewType {
  GROUP_REVIEW_STATS = 'GROUP_REVIEW_STATS',
  GROUP_REVIEW_KEY_MEMBER = 'GROUP_REVIEW_KEY_MEMBER',
  MEMBER_REVIEW_STATS = 'MEMBER_REVIEW_STATS',
  MEMBER_REVIEW_GRATITUDE_ENTRY = 'MEMBER_REVIEW_GRATITUDE_ENTRY',
}
